sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev
    - libgsl0-dev
    - liblapack-dev
    - libatlas-base-dev

env:
  matrix:
  - ARGS="--resolver lts-11.3" GHCVER=8.2.2 PUBLISH_DOCS=true
  - ARGS="--resolver nightly-2018-04-05" GHCVER=8.4.1 PUBLISH_DOCS=false
  global:
  - SHCVER=0.0.4.0
  - SHC_GHCVER=8.0.1
  - secure: "yN3nC3elw/fbdktDPA4G6Cn7gB8bmAPV2QSnNxy13cJ+hpHmpyFxXp1H+gD/1r3j+U4rzoXA0fDjz92GtmolwDUp1DExxhf6OeIezx30O1wuexrIVmsbZj9/xMkV05BuYmRPl1a+TqaMig89/lcrjBLRcq4JaIRmejmQCsXZ9f5DbTVm1qIBysA2GWqgAvvD6czYk7yPA6w6eknALkx4OgTuCuF/LWeVOpcOZi2fOtSxQTylE6xQkPVSBxF4oXaYrKs77L85UYtMefuhcbiyiMCqEMsnxXzBzX7NjqhKM+TPOn0D5HD8tOBkN2gCyX4HuDQJSODXhp9/McEx798x4ueDQPALKdrQ6jJCMS4skc51uyek5ZEcnrfSiAvnqMeuAXCJMDlpHx5nGrbJ9KvJ0Rahqvg4arYE1pav6XXnuNCZPXB/Hn3Mbiou5vuTzZweaMBzk5J/bohMDiygAvkWVAzujBwChlVWDqE3W/rFOpgFIVtMzza5ZaVuDJB/PFdLTSQ4dyy0qMcNuIMG+lcvN01qF7HT+sMD4dS6lNhsY6uMmbwZm21Yf+Gd6a2+7o/oLxWoxmDcmMrFbyPLolsNWtoJDYDatBuC6/GpE+lPpXAAozvIhvOT0fReFoP4wGb4SPr1TsN+owzxVsLLRMGpKMTW7SwneFNCPSn8TAQOJNQ="

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal $ARGS setup
- stack --no-terminal $ARGS install hscolour
- stack $ARGS ghc -- --version

script:
- stack --no-terminal $ARGS test :mltool-test --test-arguments="--plain" --haddock --no-haddock-deps --coverage

after_success:
- rake publish_docs
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v$SHCVER/shc-linux-x64-$SHC_GHCVER.tar.bz2 | tar -xj
- ./shc mltool mltool-test


cache:
  directories:
  - $HOME/.stack
